# Generated by Django 5.1.4 on 2024-12-09 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0004_postprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postprofile',
        ),
    ]
