# Generated by Django 5.1.4 on 2024-12-09 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0006_post_no_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='no_like',
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='CORE.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='no_like',
            field=models.ManyToManyField(blank=True, default=0, related_name='liked_posts', to='CORE.user'),
        ),
    ]
