# Generated by Django 5.1.4 on 2024-12-09 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0007_remove_post_no_like_alter_post_user_post_no_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='no_like',
        ),
        migrations.AddField(
            model_name='post',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CORE.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CORE.user')),
            ],
        ),
    ]
