# Generated by Django 5.1.4 on 2024-12-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0009_addfriend'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addfriend',
            unique_together={('user', 'friend')},
        ),
        migrations.AddConstraint(
            model_name='addfriend',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('friend')), _negated=True), name='prevent_self_friendship'),
        ),
    ]
