# Generated by Django 5.1.4 on 2024-12-10 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0011_message_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_conversations', to='CORE.user'),
        ),
    ]
