# Generated by Django 5.1.4 on 2024-12-10 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0012_alter_conversation_user2'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('user1', 'user2')},
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='CORE.conversation'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user2', to='CORE.user'),
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='messages',
        ),
    ]
