# Generated by Django 5.1.4 on 2024-12-10 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0014_remove_message_conversation_remove_message_recipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='CORE.convsersation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CORE.user')),
            ],
        ),
    ]
