# Generated by Django 5.1.3 on 2024-12-16 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0016_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
