# Generated by Django 5.1.3 on 2024-12-20 23:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0020_remove_post_post_image_postimage_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
